// Code generated by "stringer -type=PrimitiveType -output=type_identifiers_string.go"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeVoid-0]
	_ = x[TypeScalar-1]
	_ = x[TypeBoolean-2]
	_ = x[TypeFloat-3]
	_ = x[TypeString-4]
	_ = x[TypeBytes-5]
	_ = x[TypeArray-6]
	_ = x[TypeMap-7]
	_ = x[TypeStruct-8]
}

const _PrimitiveType_name = "TypeVoidTypeScalarTypeBooleanTypeFloatTypeStringTypeBytesTypeArrayTypeMapTypeStruct"

var _PrimitiveType_index = [...]uint8{0, 8, 18, 29, 38, 48, 57, 66, 73, 83}

func (i PrimitiveType) String() string {
	if i >= PrimitiveType(len(_PrimitiveType_index)-1) {
		return "PrimitiveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PrimitiveType_name[_PrimitiveType_index[i]:_PrimitiveType_index[i+1]]
}
