// Code generated by "stringer -type=CompressionMethod -output=compression_string.go"; DO NOT EDIT.

package wire

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressionMethodNone-0]
	_ = x[CompressionMethodGzip-1]
}

const _CompressionMethod_name = "CompressionMethodNoneCompressionMethodGzip"

var _CompressionMethod_index = [...]uint8{0, 21, 42}

func (i CompressionMethod) String() string {
	if i < 0 || i >= CompressionMethod(len(_CompressionMethod_index)-1) {
		return "CompressionMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CompressionMethod_name[_CompressionMethod_index[i]:_CompressionMethod_index[i+1]]
}
